version: '3.9'

services:
  frontend:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    volumes:
      - ./FrontEnd/PostPilot-frontEND:/app
      - /app/node_modules
      - ./FrontEnd/PostPilot-frontEND/dist:/app/dist  
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - postpilot_network

  backend:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    volumes:
      - ./BackEnd:/app
    ports:
      - "5000:5000"
    depends_on:
      - frontend
      - mongodb
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - MONGODB_HOST=${MONGODB_HOST}
    networks:
      - postpilot_network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./DataBase:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    networks:
      - postpilot_network

networks:
  postpilot_network:
    driver: bridge