version: '3.9'

services:
  frontend:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    volumes:
      - ./FrontEnd/PostPilot-frontEND:/app
      - /app/node_modules
      - ./FrontEnd/PostPilot-frontEND/dist:/app/dist  
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    volumes:
      - ./BackEnd:/app
    ports:
      - "5000:5000"
    depends_on:
      - frontend
